### ISSUE TITLE
Onkyo script crashes SmartThings hub

### ISSUE THREAD

**Issue by PunditSharp** [allanak/SmartThings#1]
Created DeviceHandler for my Onkyo TX-NR616.  The device shows up in my home, but when I send a command (e.g. a mute), it crashes the SmartThings hub!  There doesn't seem to be anything logged to show what causes the crash.  Any thoughts on this?

**Comment by jasonbade** [comment]
The constant crashing was fixed with the latest SmartThings update (000.016.00013).
