### ISSUE TITLE
failing to add receiver

### ISSUE THREAD

**Issue by Airyphyla** [allanak/SmartThings#3]
Hello there,

Could you help me add my receiver NR-626, after publishing your devicehandler, ST wont detect it.
I didnt fully understand how to modify the ip into the code (or shouldnt i?)

in advance, thanks for your help.
Greetings,

**Comment by jasonbade** [comment]
For my NR656 to work, I had to comment out the line with "0D" at the end of
the device handler code, and use "0A" as shown below...

[image: Inline image 5]

The device handler won't go out a check for new devices.  You'll have to
add the device handler, then manually add the device.

To create device, click on "Devices", and "New Device"
[image: Inline image 1]


Enter
[image: Inline image 7]

Let me know if this helps or if you need additional help.

Jason

**Comment by allanak** [comment]
@Airyphyla @jasonbade  is correct. There is no autodiscovery. You need to add the device using the hex converted IP:port combination as mentioned in step 3 of the comments inside the groovy code.

**Comment by Airyphyla** [comment]
Yes, thanks guys...ive made it work! thanks alot.

**Comment by allanak** [comment]
Closing this out.
