### ISSUE TITLE
TX-NR646 issues

### ISSUE THREAD

**Issue by slappula** [allanak/SmartThings#5]
I apologize in advance if this is the wrong place for this.  I just wanted to leave a comment that might help someone in the future if they're having problems getting this working.  Feel free to close this immediately.  Two things I ran into when trying to get my TX-NR646 setup:

1. When you convert the IP address to hexadecimal, make sure to remove the leading '0x' (example: Mine converted to 0x0A00010C, but I needed to setup the SmartThings Device Network ID using just 0A00010C.

2. I used the Excel document called 'ISCP_AVR_2014.Models' found [here](https://github.com/miracle2k/onkyo-eiscp) (the CMND MAIN tab) to modify the codes and devices that allanak originally setup.  One code that was missing was the Stream Box input (HDMI 3).  It is SLI11.

This one isn't that big a deal (more cosmetic than anything), but I found this post about icons useful when changing up the inputs icons:

https://community.smartthings.com/t/where-are-the-tile-icons/40086/17

Lastly- thank you allanak!!!!  This allowed me to save $70 that I would have spent on another Harmony Hub.

**Comment by allanak** [comment]
No worries, glad I could help! I am actually in the process of migrating away from ST and going to Home Assistant this weekend so your timing is pretty funny
