### ISSUE TITLE
Not possible to create 2 or more devices using device handler, refering to same physical amplituner

### ISSUE THREAD

**Issue by btrial** [allanak/SmartThings#6]
Hi, it is not possible to create 2 or more devices using such device handler, which should refer to same physical amplituner. 

That is becuase "device network ID" must be unique in SmartThings.

Could you refactor your code, to be able to pass "device network ID" as a parameter, and not to set it in devices "device network ID" field ?

I tried that but it didn't work:

new physicalgraph.device.HubAction(msg,physicalgraph.device.Protocol.LAN, "C0A8012B:EAE0");

**Comment by allanak** [comment]
I'm sure it's doable but I migrated away from SmartThings about a year ago so I'm not in a position to rewrite/test this. Happy to take a pull request if you figure it out though!

**Comment by btrial** [comment]
what have you migrated to ?

**Comment by allanak** [comment]
@btrial HomeAssistant
